### ISSUE TITLE
Build emscripten version

### ISSUE THREAD

**Issue by netantho** [ThibaultReuille/graphiti#4]
Hi,

I tried to build the emscripten version of graphiti on Mac.
Here is more or less what I did:

```
cd ..
git clone https://github.com/kripken/emscripten.git

vim graphiti/Makefile:
  EM_CC=../emscripten/em++

make web

cd /tmp
wget http://llvm.org/releases/3.3/clang+llvm-3.3-x86_64-apple-darwin12.tar.gz
tar xvzf clang+llvm-3.3-x86_64-apple-darwin12.tar.gz
vim ~/.emscripten
  LLVM_ROOT = os.path.expanduser(os.getenv('LLVM') or '/private/tmp/clang+llvm-3.3-x86_64-apple-darwin12/bin') # directory

export EMCC_FAST_COMPILER=0
make web
```

I get the following error:

```
--- Compiling with Emscripten ---
../emscripten/em++ -std=c++11 -I./ -I../ -I../raindance -I../raindance/Lib -I../raindance/Lib/glm-0.9.5.4 Main.cc -s FULL_ES2=1 -s TOTAL_MEMORY=268435456 -o Web/graphiti.js -s EXPORTED_FUNCTIONS=" [ '_create', '_destroy', '_initialize', '_start', '_registerScript', '_setAttribute', '_addNode', '_removeNode', '_countNodes', '_getNodeID', '_setNodeLabel', '_getNodeLabel', '_setNodeMark', '_getNodeMark', '_setNodeWeight', '_getNodeWeight', '_setNodeAttribute', '_addLink', '_removeLink', '_countLinks', '_getLinkID', '_getLinkNode1', '_getLinkNode2', '_setLinkAttribute', '_countSelectedNodes', '_getSelectedNode', ]"
clang: warning: argument unused during compilation: '-nostdinc++'
In file included from Main.cc:29:
In file included from ./Graphiti.hh:3:
In file included from ../raindance/Raindance.hh:4:
In file included from ../raindance/Core/Context.hh:3:
../raindance/Core/Clock.hh:24:78: warning: format specifies type 'int' but the argument has type 'suseconds_t' (aka 'long')
      [-Wformat]
        LOG("[CLOCK] Clock created at (%ld s, %d us).\n", m_ZeroTime.tv_sec, m_ZeroTime.tv_usec);
                                              ~~                             ^~~~~~~~~~~~~~~~~~
                                              %ld
../raindance/Core/Log.hh:6:43: note: expanded from macro 'LOG'
# define LOG(fmt, ...) do { printf(fmt, ##__VA_ARGS__); } while(false)
                                          ^
1 warning generated.
warning: unresolved symbol: glGetTexImage

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'Web/graphiti.js.map'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at generateMap (/Users/averez/Hack/opendns/dataviz/emscripten/tools/source-maps/sourcemapper.js:150:6)
    at Object.<anonymous> (/Users/averez/Hack/opendns/dataviz/emscripten/tools/source-maps/sourcemapper.js:204:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Traceback (most recent call last):
  File "/Users/averez/Hack/opendns/dataviz/emscripten/emcc", line 2014, in <module>
    if debug_level >= 4: generate_source_map(target)
  File "/Users/averez/Hack/opendns/dataviz/emscripten/emcc", line 1859, in generate_source_map
    '--offset', str(offset)])
  File "/Users/averez/Hack/opendns/dataviz/emscripten/tools/jsrun.py", line 43, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/usr/local/bin/node', '/Users/averez/Hack/opendns/dataviz/emscripten/tools/source-maps/sourcemapper.js', '/tmp/tmpedwSg9/graphiti.bc.link.ll.o.js', '--sourceRoot', '/Users/averez/Hack/opendns/dataviz/graphiti', '--mapFileBaseName', 'Web/graphiti.js', '--offset', '0'] to finish with return code 0, but it returned with code 8 instead! Output:
make: *** [web] Error 1
```

I don't have a Web folder generated.

Docs about the emscripten build would be helpful.

Thanks!

**Comment by tpacker** [comment]
I am having related problems building the web version of OpenGraphiti.  I downloaded and built the most recent code yesterday.  Had a few issues along the way, but finally got it to build, run, and show my own data.  Now, as I move on to the Web version, it builds with warnings:


$ cd /path/to/opengraphiti/dataviz/graphiti
$ make webrun
( cd ../raindance && make )
make[1]: Entering directory '/path/to/opengraphiti/dataviz/raindance'
--- Packing Raindance resources ---
./pack.sh
- Packing Shaders
- Packing Shaders/Primitives
- Packing Shaders/Widgets
- Packing Shaders/Charts
- Packing Textures
- Packing Textures/Shapes
make[1]: Leaving directory '/path/to/opengraphiti/dataviz/raindance'
--- Packing OpenGraphiti resources ---
./pack.sh
--- Compiling web version with Emscripten ---
mkdir -p Web
/path/to/opengraphiti/emsdk_portable/emscripten/master/em++ --bind -std=c++11 -I./ -I../ -I../raindance/Lib/glm-0.9.5.4 Main.cc -s FULL_ES2=1 -s TOTAL_MEMORY=268435456 -o Web/graphiti.html
INFO     root: (Emscripten: Running sanity checks)
warning: unresolved symbol: glGetTexImage
warning: unresolved symbol: glutSetWindow
--- Appending launcher script to Web/graphiti.html ---
echo "<script async src='../Javascript/main.js'></script>" >> Web/graphiti.html


and runs only partially. I can see the UI when I put my .json file at the bottom of the graphiti.html file, but no data.  If I don't put a link to my .json file in the .html file then the window is all black.  There are console errors either way:


[CANVAS] Creating FrameBuffer Object 1327x806 ...
graphiti.html (line 1233)
[post-exception status] Exception thrown, see JavaScript console
	

console.error(text);

graphiti.html (line 1245)
uncaught exception: SimulateInfiniteLoop
missing function: glutSetWindow
	

console.error(text);

graphiti.html (line 1245)
-1
graphiti.html (line 1233)
-1
	

console.error(text);

graphiti.html (line 1245)
[post-exception status] Exception thrown, see JavaScript console
	

console.error(text);

graphiti.html (line 1245)
uncaught exception: abort(-1) at jsStackTrace@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:1161:13
stackTrace@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:1178:22
abort@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:237505:44
_glutSetWindow@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:10883:58
__ZN9RainDance13postRedisplayEv [RainDance::postRedisplay()]@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:20761:3
__ZN8Graphiti4idleEv [Graphiti::idle()]@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:22947:2
__ZN4GLUTL4idleEv [GLUT(idle)]@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:20850:2
dynCall_v@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:232874:3
Runtime.dynCall@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:280:14
callback@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:8521:11
Browser.safeSetTimeout/<@file:///path/to/opengraphiti/dataviz/graphiti/Web/graphiti.js:7594:13


Is there a tutorial for getting Web to work?
